/* Pratsia — UI translations and job catalogue (hr = Croatian, uk = Ukrainian, ru = Russian) */

const UI = {
  hr: {
    langName: "Hrvatski",
    nav_categories: "Kategorije poslova",
    nav_how: "Kako funkcionira",
    nav_contact: "Kontakt",
    hero_kicker: "Pratsia — posredovanje pri zapošljavanju",
    hero_title: "Posao u Hrvatskoj za ukrajinske državljane",
    hero_subtitle: "Povezujemo ukrajinske radnike s poslodavcima diljem Hrvatske. Pregledajte otvorene pozicije po kategorijama i prijavite se u nekoliko klikova.",
    hero_cta: "Pogledaj otvorene pozicije",
    how_title: "Kako funkcionira",
    how_1_title: "Odaberite posao",
    how_1_text: "Pregledajte kategorije i pronađite poziciju koja vam odgovara.",
    how_2_title: "Pošaljite prijavu",
    how_2_text: "Ispunite kratki obrazac i priložite svoj životopis (CV).",
    how_3_title: "Javljamo vam se",
    how_3_text: "Naš tim kontaktira vas i povezuje s poslodavcem.",
    categories_title: "Kategorije poslova",
    categories_subtitle: "Odaberite kategoriju i pogledajte trenutno otvorene pozicije.",
    job_requirements: "Što nudimo / uvjeti",
    job_apply: "Prijavi se za ovaj posao",
    form_name: "Ime i prezime",
    form_email: "E-mail adresa",
    form_phone: "Broj telefona",
    form_message: "Poruka (nije obavezno)",
    form_cv: "Upload CV-a (PDF, DOCX ili JPG, do 5 MB)",
    form_submit: "Pošalji prijavu",
    form_sending: "Slanje...",
    form_success: "Hvala! Vaša prijava je uspješno poslana. Javit ćemo vam se uskoro.",
    form_error: "Došlo je do greške pri slanju. Pokušajte ponovno ili nam pišite izravno na",
    form_error_filetype: "Nedozvoljen format datoteke. Dopušteni formati: PDF, DOCX, JPG.",
    form_error_filesize: "Datoteka je prevelika. Najveća dopuštena veličina je 5 MB.",
    form_required: "Molimo ispunite sva obavezna polja.",
    footer_tagline: "Pratsia povezuje ukrajinske radnike s poslodavcima u Hrvatskoj.",
    footer_contact: "Kontakt",
    footer_rights: "Sva prava pridržana.",
  },
  uk: {
    langName: "Українська",
    nav_categories: "Категорії вакансій",
    nav_how: "Як це працює",
    nav_contact: "Контакти",
    hero_kicker: "Pratsia — агенція працевлаштування",
    hero_title: "Робота в Хорватії для громадян України",
    hero_subtitle: "Ми поєднуємо українських працівників з роботодавцями по всій Хорватії. Перегляньте вакансії за категоріями та подайте заявку за кілька кліків.",
    hero_cta: "Переглянути вакансії",
    how_title: "Як це працює",
    how_1_title: "Оберіть вакансію",
    how_1_text: "Перегляньте категорії та знайдіть підходящу позицію.",
    how_2_title: "Надішліть заявку",
    how_2_text: "Заповніть коротку форму та прикріпіть своє резюме (CV).",
    how_3_title: "Ми зв'яжемось з вами",
    how_3_text: "Наша команда зв'яжеться з вами та з'єднає з роботодавцем.",
    categories_title: "Категорії вакансій",
    categories_subtitle: "Оберіть категорію та перегляньте актуальні вакансії.",
    job_requirements: "Що ми пропонуємо / умови",
    job_apply: "Подати заявку на цю вакансію",
    form_name: "Ім'я та прізвище",
    form_email: "Електронна пошта",
    form_phone: "Номер телефону",
    form_message: "Повідомлення (необов'язково)",
    form_cv: "Завантажити CV (PDF, DOCX або JPG, до 5 МБ)",
    form_submit: "Надіслати заявку",
    form_sending: "Надсилання...",
    form_success: "Дякуємо! Вашу заявку успішно надіслано. Ми скоро з вами зв'яжемось.",
    form_error: "Сталася помилка під час надсилання. Спробуйте ще раз або напишіть нам напряму на",
    form_error_filetype: "Недопустимий формат файлу. Дозволені формати: PDF, DOCX, JPG.",
    form_error_filesize: "Файл завеликий. Максимальний розмір — 5 МБ.",
    form_required: "Будь ласка, заповніть усі обов'язкові поля.",
    footer_tagline: "Pratsia поєднує українських працівників з роботодавцями в Хорватії.",
    footer_contact: "Контакти",
    footer_rights: "Усі права захищені.",
  },
  ru: {
    langName: "Русский",
    nav_categories: "Категории вакансий",
    nav_how: "Как это работает",
    nav_contact: "Контакты",
    hero_kicker: "Pratsia — агентство трудоустройства",
    hero_title: "Работа в Хорватии для граждан Украины",
    hero_subtitle: "Мы соединяем украинских работников с работодателями по всей Хорватии. Просмотрите вакансии по категориям и подайте заявку в несколько кликов.",
    hero_cta: "Смотреть вакансии",
    how_title: "Как это работает",
    how_1_title: "Выберите вакансию",
    how_1_text: "Просмотрите категории и найдите подходящую позицию.",
    how_2_title: "Отправьте заявку",
    how_2_text: "Заполните короткую форму и прикрепите своё резюме (CV).",
    how_3_title: "Мы свяжемся с вами",
    how_3_text: "Наша команда свяжется с вами и соединит с работодателем.",
    categories_title: "Категории вакансий",
    categories_subtitle: "Выберите категорию и просмотрите актуальные вакансии.",
    job_requirements: "Что мы предлагаем / условия",
    job_apply: "Подать заявку на эту вакансию",
    form_name: "Имя и фамилия",
    form_email: "Электронная почта",
    form_phone: "Номер телефона",
    form_message: "Сообщение (необязательно)",
    form_cv: "Загрузить CV (PDF, DOCX или JPG, до 5 МБ)",
    form_submit: "Отправить заявку",
    form_sending: "Отправка...",
    form_success: "Спасибо! Ваша заявка успешно отправлена. Мы скоро с вами свяжемся.",
    form_error: "Произошла ошибка при отправке. Попробуйте ещё раз или напишите нам напрямую на",
    form_error_filetype: "Недопустимый формат файла. Разрешённые форматы: PDF, DOCX, JPG.",
    form_error_filesize: "Файл слишком большой. Максимальный размер — 5 МБ.",
    form_required: "Пожалуйста, заполните все обязательные поля.",
    footer_tagline: "Pratsia соединяет украинских работников с работодателями в Хорватии.",
    footer_contact: "Контакты",
    footer_rights: "Все права защищены.",
  },
};

/* Minimal inline line-icons (24x24, stroke = currentColor) */
const ICONS = {
  construction: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18"/><path d="M5 21V10l7-6 7 6v11"/><path d="M9 21v-6h6v6"/></svg>',
  hospitality: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 9h13v4a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5V9Z"/><path d="M17 10h1.5a2.5 2.5 0 0 1 0 5H17"/><path d="M8 3c0 1-1 1-1 2s1 1 1 2"/><path d="M12 3c0 1-1 1-1 2s1 1 1 2"/></svg>',
  manufacturing: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.87l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.7 1.7 0 0 0-1.87-.34 1.7 1.7 0 0 0-1 1.55V21a2 2 0 1 1-4 0v-.09A1.7 1.7 0 0 0 9 19.36a1.7 1.7 0 0 0-1.87.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.64 15a1.7 1.7 0 0 0-1.55-1H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.64 9a1.7 1.7 0 0 0-.34-1.87l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.64a1.7 1.7 0 0 0 1-1.55V3a2 2 0 1 1 4 0v.09a1.7 1.7 0 0 0 1 1.55 1.7 1.7 0 0 0 1.87-.34l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.36 9a1.7 1.7 0 0 0 1.55 1H21a2 2 0 1 1 0 4h-.09a1.7 1.7 0 0 0-1.55 1Z"/></svg>',
  agriculture: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22V12"/><path d="M12 12c0-4.5 3-8 8-8 0 4.5-3 8-8 8Z"/><path d="M12 15c0-3.5-2.5-6-6-6 0 3.5 2.5 6 6 6Z"/></svg>',
  logistics: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 8 12 3 3 8v8l9 5 9-5V8Z"/><path d="M3 8l9 5 9-5"/><path d="M12 13v8"/></svg>',
  cleaning: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 4 5 13l3 3 9-9-3-3Z"/><path d="M5 13l-2 6 6-2"/><path d="M14 4l3-1 1 1-1 3"/></svg>',
  care: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20.8 8.6c0 4.2-8.8 10.4-8.8 10.4S3.2 12.8 3.2 8.6a4.6 4.6 0 0 1 8.8-1.8 4.6 4.6 0 0 1 8.8 1.8Z"/><path d="M12 8v5"/><path d="M9.5 10.5h5"/></svg>',
  admin: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="13" rx="1.5"/><path d="M8 21h8"/><path d="M12 17v4"/><path d="M7 9h10M7 12h6"/></svg>',
};

/* Job catalogue. Each job/category has hr/uk/ru strings. */
const CATEGORIES = [
  {
    id: "construction",
    icon: "construction",
    name: { hr: "Građevinarstvo", uk: "Будівництво", ru: "Строительство" },
    jobs: [
      {
        id: "construction-worker",
        title: { hr: "Građevinski radnik", uk: "Будівельник", ru: "Строительный рабочий" },
        desc: {
          hr: "Radovi na gradilištu: pomoćni i izvođački poslovi na novogradnjama i rekonstrukcijama diljem Hrvatske.",
          uk: "Робота на будівельному майданчику: допоміжні та виконавчі роботи на новобудовах і реконструкціях по всій Хорватії.",
          ru: "Работа на стройплощадке: вспомогательные и исполнительные работы на новостройках и реконструкциях по всей Хорватии.",
        },
        reqs: {
          hr: ["Smještaj osiguran", "Plaća isplaćena redovito mjesečno", "Pomoć oko radne dozvole i dokumentacije"],
          uk: ["Житло забезпечено", "Регулярна щомісячна виплата зарплати", "Допомога з дозволом на роботу та документами"],
          ru: ["Жильё предоставляется", "Регулярная ежемесячная зарплата", "Помощь с разрешением на работу и документами"],
        },
      },
      {
        id: "rebar-worker",
        title: { hr: "Armirač", uk: "Арматурник", ru: "Арматурщик" },
        desc: {
          hr: "Postavljanje i vezivanje armature prema projektnoj dokumentaciji na građevinskim projektima.",
          uk: "Встановлення та в'язання арматури згідно з проєктною документацією на будівельних об'єктах.",
          ru: "Установка и вязка арматуры согласно проектной документации на строительных объектах.",
        },
        reqs: {
          hr: ["Prethodno iskustvo poželjno, ne i obavezno", "Radna oprema osigurana", "Prijevoz do gradilišta organiziran"],
          uk: ["Досвід бажаний, але не обов'язковий", "Робоче спорядження надається", "Транспорт до об'єкта організовано"],
          ru: ["Опыт желателен, но не обязателен", "Рабочая экипировка предоставляется", "Организован транспорт до объекта"],
        },
      },
      {
        id: "carpenter",
        title: { hr: "Tesar", uk: "Тесляр", ru: "Плотник" },
        desc: {
          hr: "Izrada oplata, krovnih konstrukcija i drugih drvenih elemenata na gradilištima.",
          uk: "Виготовлення опалубки, покрівельних конструкцій та інших дерев'яних елементів на будмайданчиках.",
          ru: "Изготовление опалубки, кровельных конструкций и других деревянных элементов на стройках.",
        },
        reqs: {
          hr: ["Konkurentna satnica", "Mogućnost stalnog zaposlenja", "Tim koji govori ukrajinski/ruski na gradilištu"],
          uk: ["Конкурентна погодинна оплата", "Можливість постійного працевлаштування", "Команда, що розмовляє українською/російською"],
          ru: ["Конкурентная почасовая оплата", "Возможность постоянного трудоустройства", "Команда, говорящая на украинском/русском"],
        },
      },
    ],
  },
  {
    id: "hospitality",
    icon: "hospitality",
    name: { hr: "Ugostiteljstvo i turizam", uk: "Готельно-ресторанний бізнес і туризм", ru: "Гостинично-ресторанный бизнес и туризм" },
    jobs: [
      {
        id: "waiter",
        title: { hr: "Konobar / Konobarica", uk: "Офіціант / Офіціантка", ru: "Официант / Официантка" },
        desc: {
          hr: "Posluživanje gostiju u restoranima i hotelima na hrvatskoj obali tijekom sezone i cijele godine.",
          uk: "Обслуговування гостей у ресторанах та готелях на хорватському узбережжі в сезон і цілий рік.",
          ru: "Обслуживание гостей в ресторанах и отелях на хорватском побережье в сезон и круглый год.",
        },
        reqs: {
          hr: ["Smještaj i prehrana uključeni", "Napojnice", "Osnovno znanje engleskog poželjno"],
          uk: ["Житло та харчування включені", "Чайові", "Базове знання англійської бажане"],
          ru: ["Проживание и питание включены", "Чаевые", "Базовое знание английского желательно"],
        },
      },
      {
        id: "cook",
        title: { hr: "Kuhar / Kuharica", uk: "Кухар / Кухарка", ru: "Повар" },
        desc: {
          hr: "Priprema jela u kuhinjama restorana i hotela, rad u timu pod vodstvom glavnog kuhara.",
          uk: "Приготування страв на кухнях ресторанів і готелів, робота в команді під керівництвом шеф-кухаря.",
          ru: "Приготовление блюд на кухнях ресторанов и отелей, работа в команде под руководством шеф-повара.",
        },
        reqs: {
          hr: ["Radno iskustvo u kuhinji poželjno", "Smještaj osiguran", "Mogućnost produljenja ugovora"],
          uk: ["Досвід роботи на кухні бажаний", "Житло забезпечено", "Можливість продовження контракту"],
          ru: ["Опыт работы на кухне желателен", "Жильё предоставляется", "Возможность продления контракта"],
        },
      },
      {
        id: "housekeeper",
        title: { hr: "Sobarica / Sobar", uk: "Покоївка", ru: "Горничная" },
        desc: {
          hr: "Održavanje čistoće i reda hotelskih soba i zajedničkih prostora.",
          uk: "Підтримання чистоти й порядку в готельних номерах та спільних приміщеннях.",
          ru: "Поддержание чистоты и порядка в гостиничных номерах и общих помещениях.",
        },
        reqs: {
          hr: ["Fleksibilno radno vrijeme", "Bez potrebnog iskustva", "Smještaj u blizini hotela"],
          uk: ["Гнучкий графік роботи", "Досвід не обов'язковий", "Житло поблизу готелю"],
          ru: ["Гибкий график работы", "Опыт не требуется", "Жильё рядом с отелем"],
        },
      },
    ],
  },
  {
    id: "manufacturing",
    icon: "manufacturing",
    name: { hr: "Proizvodnja i tvornice", uk: "Виробництво", ru: "Производство" },
    jobs: [
      {
        id: "production-worker",
        title: { hr: "Radnik u proizvodnji", uk: "Робітник виробництва", ru: "Рабочий на производстве" },
        desc: {
          hr: "Rad na proizvodnoj liniji uz obuku na radnom mjestu, u dvije ili tri smjene.",
          uk: "Робота на виробничій лінії з навчанням на робочому місці, у дві або три зміни.",
          ru: "Работа на производственной линии с обучением на рабочем месте, в две или три смены.",
        },
        reqs: {
          hr: ["Obuka na radnom mjestu", "Prijevoz organiziran", "Bonusi za redovitost"],
          uk: ["Навчання на робочому місці", "Транспорт організовано", "Бонуси за регулярність"],
          ru: ["Обучение на рабочем месте", "Организован транспорт", "Бонусы за регулярность"],
        },
      },
      {
        id: "cnc-operator",
        title: { hr: "Operater CNC stroja", uk: "Оператор верстата з ЧПУ", ru: "Оператор станка с ЧПУ" },
        desc: {
          hr: "Rukovanje i nadzor CNC strojeva u metaloprerađivačkoj proizvodnji.",
          uk: "Керування та нагляд за верстатами з ЧПУ на металообробному виробництві.",
          ru: "Управление и контроль станков с ЧПУ на металлообрабатывающем производстве.",
        },
        reqs: {
          hr: ["Tehničko iskustvo poželjno", "Viša satnica za smjenski rad", "Mogućnost napredovanja"],
          uk: ["Технічний досвід бажаний", "Вища ставка за позмінну роботу", "Можливість кар'єрного росту"],
          ru: ["Технический опыт желателен", "Более высокая ставка за сменную работу", "Возможность карьерного роста"],
        },
      },
      {
        id: "packer",
        title: { hr: "Radnik na pakiranju", uk: "Пакувальник", ru: "Упаковщик" },
        desc: {
          hr: "Pakiranje gotovih proizvoda i kontrola kvalitete prije otpreme.",
          uk: "Пакування готової продукції та контроль якості перед відправленням.",
          ru: "Упаковка готовой продукции и контроль качества перед отправкой.",
        },
        reqs: {
          hr: ["Nije potrebno prethodno iskustvo", "Fizički lagan posao", "Redovita isplata plaće"],
          uk: ["Досвід не потрібен", "Фізично легка робота", "Регулярна виплата зарплати"],
          ru: ["Опыт не требуется", "Физически лёгкая работа", "Регулярная выплата зарплаты"],
        },
      },
    ],
  },
  {
    id: "agriculture",
    icon: "agriculture",
    name: { hr: "Poljoprivreda", uk: "Сільське господарство", ru: "Сельское хозяйство" },
    jobs: [
      {
        id: "seasonal-farm-worker",
        title: { hr: "Sezonski radnik u poljoprivredi", uk: "Сезонний працівник у сільському господарстві", ru: "Сезонный работник в сельском хозяйстве" },
        desc: {
          hr: "Berba i obrada poljoprivrednih kultura tijekom sezone na obiteljskim gospodarstvima i plantažama.",
          uk: "Збір та обробка сільськогосподарських культур у сезон на фермерських господарствах і плантаціях.",
          ru: "Сбор и обработка сельскохозяйственных культур в сезон на фермерских хозяйствах и плантациях.",
        },
        reqs: {
          hr: ["Smještaj na imanju", "Rad na otvorenom", "Mogućnost sezonskog ili stalnog angažmana"],
          uk: ["Житло на території господарства", "Робота на відкритому повітрі", "Сезонна або постійна зайнятість"],
          ru: ["Жильё на территории хозяйства", "Работа на открытом воздухе", "Сезонная или постоянная занятость"],
        },
      },
      {
        id: "greenhouse-worker",
        title: { hr: "Radnik u staklenicima", uk: "Робітник теплиці", ru: "Работник теплицы" },
        desc: {
          hr: "Njega i berba povrća u staklenicima, rad tijekom cijele godine.",
          uk: "Догляд і збір овочів у теплицях, робота цілий рік.",
          ru: "Уход и сбор овощей в теплицах, работа круглый год.",
        },
        reqs: {
          hr: ["Rad tijekom cijele godine", "Zaštitna oprema osigurana", "Smještaj u blizini"],
          uk: ["Робота цілий рік", "Захисне спорядження надається", "Житло поруч"],
          ru: ["Работа круглый год", "Защитная экипировка предоставляется", "Жильё рядом"],
        },
      },
    ],
  },
  {
    id: "logistics",
    icon: "logistics",
    name: { hr: "Skladištenje i logistika", uk: "Склад і логістика", ru: "Склад и логистика" },
    jobs: [
      {
        id: "warehouse-worker",
        title: { hr: "Skladišni radnik", uk: "Складський працівник", ru: "Работник склада" },
        desc: {
          hr: "Zaprimanje, slaganje i priprema robe za otpremu u distribucijskim centrima.",
          uk: "Приймання, розкладання та підготовка товарів до відправлення в дистрибуційних центрах.",
          ru: "Приёмка, размещение и подготовка товаров к отправке в распределительных центрах.",
        },
        reqs: {
          hr: ["Rad u zatvorenom prostoru", "Redovite smjene", "Mogućnost prekovremenog rada"],
          uk: ["Робота в приміщенні", "Регулярні зміни", "Можливість понаднормової роботи"],
          ru: ["Работа в помещении", "Регулярные смены", "Возможность сверхурочной работы"],
        },
      },
      {
        id: "forklift-operator",
        title: { hr: "Viličarist", uk: "Водій навантажувача", ru: "Водитель погрузчика" },
        desc: {
          hr: "Rukovanje viličarom pri utovaru i istovaru robe u skladištu.",
          uk: "Керування навантажувачем при завантаженні та розвантаженні товару на складі.",
          ru: "Управление погрузчиком при загрузке и разгрузке товара на складе.",
        },
        reqs: {
          hr: ["Certifikat za viličar poželjan (pomažemo pri stjecanju)", "Viša satnica", "Stalno zaposlenje"],
          uk: ["Сертифікат водія навантажувача бажаний (допомагаємо отримати)", "Вища погодинна оплата", "Постійна робота"],
          ru: ["Сертификат водителя погрузчика желателен (помогаем получить)", "Более высокая почасовая оплата", "Постоянная работа"],
        },
      },
      {
        id: "delivery-driver",
        title: { hr: "Vozač dostave", uk: "Водій доставки", ru: "Водитель доставки" },
        desc: {
          hr: "Dostava paketa i robe klijentima na određenom području.",
          uk: "Доставка посилок і товарів клієнтам на визначеній території.",
          ru: "Доставка посылок и товаров клиентам на определённой территории.",
        },
        reqs: {
          hr: ["Vozačka dozvola B kategorije", "Vozilo osigurava poslodavac", "Bonus po broju dostava"],
          uk: ["Посвідчення водія категорії B", "Автомобіль надає роботодавець", "Бонус за кількість доставок"],
          ru: ["Водительское удостоверение категории B", "Автомобиль предоставляет работодатель", "Бонус за количество доставок"],
        },
      },
    ],
  },
  {
    id: "cleaning",
    icon: "cleaning",
    name: { hr: "Čišćenje i održavanje", uk: "Прибирання та обслуговування", ru: "Уборка и обслуживание" },
    jobs: [
      {
        id: "cleaner",
        title: { hr: "Čistačica / Čistač", uk: "Прибиральниця / Прибиральник", ru: "Уборщица / Уборщик" },
        desc: {
          hr: "Čišćenje poslovnih prostora, hotela ili privatnih objekata.",
          uk: "Прибирання офісних приміщень, готелів або приватних об'єктів.",
          ru: "Уборка офисных помещений, отелей или частных объектов.",
        },
        reqs: {
          hr: ["Fleksibilno radno vrijeme", "Sredstva za čišćenje osigurana", "Rad u blizini mjesta stanovanja"],
          uk: ["Гнучкий графік роботи", "Засоби для прибирання надаються", "Робота поблизу місця проживання"],
          ru: ["Гибкий график работы", "Средства для уборки предоставляются", "Работа рядом с местом проживания"],
        },
      },
      {
        id: "maintenance-worker",
        title: { hr: "Kućni majstor (održavanje)", uk: "Технік з обслуговування будівель", ru: "Техник по обслуживанию зданий" },
        desc: {
          hr: "Manji popravci i redovito održavanje stambenih i poslovnih zgrada.",
          uk: "Дрібний ремонт та регулярне обслуговування житлових і офісних будівель.",
          ru: "Мелкий ремонт и регулярное обслуживание жилых и офисных зданий.",
        },
        reqs: {
          hr: ["Osnovno tehničko znanje", "Alat osiguran", "Stalno zaposlenje"],
          uk: ["Базові технічні навички", "Інструменти надаються", "Постійна робота"],
          ru: ["Базовые технические навыки", "Инструменты предоставляются", "Постоянная работа"],
        },
      },
    ],
  },
  {
    id: "care",
    icon: "care",
    name: { hr: "Njega i zdravstvo", uk: "Догляд і охорона здоров'я", ru: "Уход и здравоохранение" },
    jobs: [
      {
        id: "elderly-caregiver",
        title: { hr: "Njegovatelj/ica starijih osoba", uk: "Доглядальник/доглядальниця за літніми людьми", ru: "Сиделка / помощник по уходу за пожилыми" },
        desc: {
          hr: "Pomoć starijim osobama u svakodnevnim aktivnostima, u domovima ili ustanovama za skrb.",
          uk: "Допомога літнім людям у повсякденних справах, вдома або в закладах догляду.",
          ru: "Помощь пожилым людям в повседневных делах, на дому или в учреждениях по уходу.",
        },
        reqs: {
          hr: ["Iskustvo u njezi poželjno", "Smještaj moguć", "Stabilna dugoročna pozicija"],
          uk: ["Досвід у догляді бажаний", "Можливе проживання", "Стабільна довгострокова позиція"],
          ru: ["Опыт ухода желателен", "Возможно проживание", "Стабильная долгосрочная позиция"],
        },
      },
      {
        id: "nurse-technician",
        title: { hr: "Medicinska sestra / tehničar", uk: "Медична сестра / медтехнік", ru: "Медсестра / медтехник" },
        desc: {
          hr: "Rad u zdravstvenim i njegovateljskim ustanovama uz priznatu kvalifikaciju.",
          uk: "Робота в медичних та доглядових закладах за наявності визнаної кваліфікації.",
          ru: "Работа в медицинских и учреждениях по уходу при наличии признанной квалификации.",
        },
        reqs: {
          hr: ["Pomoć pri nostrifikaciji diplome", "Konkurentna plaća", "Mogućnost stalnog zaposlenja"],
          uk: ["Допомога з визнанням диплома", "Конкурентна зарплата", "Можливість постійного працевлаштування"],
          ru: ["Помощь с признанием диплома", "Конкурентная зарплата", "Возможность постоянного трудоустройства"],
        },
      },
    ],
  },
  {
    id: "admin",
    icon: "admin",
    name: { hr: "Administracija i IT", uk: "Адміністрація та ІТ", ru: "Администрация и ИТ" },
    jobs: [
      {
        id: "admin-assistant",
        title: { hr: "Administrativni referent", uk: "Адміністративний асистент", ru: "Административный ассистент" },
        desc: {
          hr: "Uredski poslovi, vođenje evidencije i podrška timu na dnevnoj bazi.",
          uk: "Офісна робота, ведення обліку та щоденна підтримка команди.",
          ru: "Офисная работа, ведение учёта и ежедневная поддержка команды.",
        },
        reqs: {
          hr: ["Rad u uredu, ugodni uvjeti", "Znanje osnovnog paketa Office", "Mogućnost rada od kuće djelomično"],
          uk: ["Офісна робота, комфортні умови", "Знання базового пакету Office", "Часткова можливість роботи з дому"],
          ru: ["Офисная работа, комфортные условия", "Знание базового пакета Office", "Частичная возможность удалённой работы"],
        },
      },
      {
        id: "translator",
        title: { hr: "Prevoditelj/ica (ukrajinski–hrvatski)", uk: "Перекладач(ка) (українська–хорватська)", ru: "Переводчик (украинский–хорватский)" },
        desc: {
          hr: "Usmeno i pisano prevođenje za potrebe poslodavaca i novih zaposlenika.",
          uk: "Усний та письмовий переклад для роботодавців і нових працівників.",
          ru: "Устный и письменный перевод для работодателей и новых сотрудников.",
        },
        reqs: {
          hr: ["Tečno znanje hrvatskog i ukrajinskog/ruskog", "Fleksibilno radno vrijeme", "Rad na daljinu moguć"],
          uk: ["Вільне володіння хорватською та українською/російською", "Гнучкий графік", "Можлива віддалена робота"],
          ru: ["Свободное владение хорватским и украинским/русским", "Гибкий график", "Возможна удалённая работа"],
        },
      },
    ],
  },
];
